# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='funcionarios')),
                ('profissao', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(help_text='Biografia do Funcionário', verbose_name='Biografia')),
                ('facebook', models.URLField(blank=True, help_text='Link para perfil')),
                ('twitter', models.URLField(blank=True, help_text='Link para perfil')),
                ('linkedin', models.URLField(blank=True, help_text='Link para perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Informacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, upload_to='projetos')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_de_realizacao', models.DateTimeField(verbose_name='Data de realização')),
                ('local_de_realizacao', models.CharField(max_length=300, verbose_name='Local de realização')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
