# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
