# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_projeto_visualizacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='visualizacoes',
        ),
    ]
