# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20160421_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='profissao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
