# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_projeto_visualizacoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Informacao',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
