# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160419_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='colunistas',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_de_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 19, 22, 18, 7, 663284, tzinfo=utc), verbose_name='Data de Publicação'),
        ),
    ]
