# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160419_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colunista',
            name='categorias',
        ),
        migrations.AddField(
            model_name='colunista',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria'),
        ),
        migrations.AlterField(
            model_name='colunista',
            name='bio',
            field=models.TextField(help_text='Biografia do Autor'),
        ),
        migrations.AlterField(
            model_name='colunista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Colunista'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_de_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 21, 18, 19, 53, 588359, tzinfo=utc), verbose_name='Data de Publicação'),
        ),
    ]
