# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160421_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colunista',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_de_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 7, 12, 31, 75713, tzinfo=utc), verbose_name='Data de Publicação'),
        ),
    ]
