# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 23:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160425_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colunista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_de_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 25, 23, 6, 33, 782321, tzinfo=utc), verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='noticias'),
        ),
    ]
