# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 00:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160425_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colunista',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='colunista',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(choices=[('Automobilismo', 'AUTO'), ('Esporte', 'ESPO'), ('Moda', 'MODA'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_de_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 26, 0, 26, 30, 707268, tzinfo=utc), verbose_name='Data de Publicação'),
        ),
        migrations.DeleteModel(
            name='Colunista',
        ),
    ]
